### ISSUE TITLE
Podspec refers to non-working tag (1.0.0)

### ISSUE THREAD

**Issue by ville-k** [Objective-Cloud/OCFWebServer#3]
The podspec available from CocoaPods points to the 1.0.0 tag of OCFWebServer that fails to build when included from a Podfile:

```
... /Pods/OCFWebServer/OCFWebServer/OCFWebServerRequest_Types.m:11:17: error: class 'OCFWebServerRequest_Types' defined without specifying a base class [-Werror,-Wobjc-root-class]
```

I can fix it locally by pointing my Podspec to the latest revision that does not include the file(OCFWebServerRequest_Types.m) that is causing the build error:

``` ruby
platform :osx, "10.9"

pod 'OCFWebServer', :git => 'https://github.com/Objective-Cloud/OCFWebServer.git', :commit => '34773776be48ebbffe4c8267a29355679f1788d0'
```

I think the fix for this would be to tag a new version and update the Podspec.

**Comment by ChristianKienle** [comment]
Thanks for reporting this issue. I have made a push a few minutes ago which fixes a few bugs and also removes support for CocoaPods.

I had too many problems with CocoaPods. I ended up spending hours just to fix CocoaPods related stuff. If you have more experience with CocoaPods feel free to send a pull request which adds the CocoaPods support back. I had it working in the past (see the 0.0.x releases) but then the problems built up. :(

**Comment by ville-k** [comment]
Great, thanks!   I'll definitely take a look at the podspec to see if I can get it working again against the latest changes.
